name: snaake
description: Snaake is a small and very simple clone of the classic snake game from Nokia phones.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.19.0
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/food/
    - assets/images/snake/
